global:
  scrape_interval: 5s
  evaluation_interval: 15s
  # scrape_timeout: 10s  # Timeout global par défaut

rule_files:
  - "rules.yml"

scrape_configs:
  # New config local
  - job_name: 'prometheus'
    static_configs:
      - targets:
          - localhost:9090
  - job_name: 'exporters'
    static_configs:
      - targets:
          - localhost:8081

  # New config docker
  # - job_name: 'prometheus'
  #   static_configs:
  #     - targets:
  #         - prometheus:9090
  # - job_name: 'exporters'
  #   static_configs:
  #     - targets:
  #         - api:8081

  # old config
  # - job_name: 'g-stock'
  #   static_configs:
  #     - targets:
  #         - localhost:8000
  # - job_name: 'crm'
  #   static_configs:
  #     - targets:
  #         - localhost:8001